version: "2"
jobs:
  build:
    docker:
      - image: circleci/node:8.1.2
    working_directory: "~/testcafe"
    steps:
      - checkout
      - setup_remote_docker  # ci中でdockerとdocker-composeを使う為の魔法のワード。ビルド用に独立した環境を作成する。
      - run: ls -l
      - run: docker-compose build
      - run: ls -l
      - run: docker-compose up