version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.2
    working_directory: "~/testcafe"
    steps:
      - checkout
      - setup_remote_docker  # ci中でdockerとdocker-composeを使う為の魔法のワード。ビルド用に独立した環境を作成する。
      - run: docker-compose build
      - run: docker-compose run testcafe
#      - run: docker-compose -f docker-compose-ci.yml run testcafe
#     Slack Orbを使ってSlackに通知
      - slack/status:
#          fail_only: true # 失敗時だけ通知する場合
          success_message: ':circleci-pass: $CIRCLE_BRANCH のデプロイが完了しました\nUser：$CIRCLE_USERNAME'
          failure_message: ':circleci-fail: $CIRCLE_BRANCH のデプロイが失敗しました\nUser：$CIRCLE_USERNAME'
          webhook: '${SLACK_WEBHOOK}'